---
kind: pipeline
type: docker
name: update

platform:
  os: linux
  arch: amd64

steps:
- name: update
  image: php:7.2-cli
  commands:
  - apt-get update && apt-get install -y --no-install-recommends libzip-dev unzip
  - docker-php-ext-install zip
  - .drone/get-composer.sh
  - php composer.phar install
  - bin/update
- name: push
  image: alpine
  commands:
  - apk add git openssh
  - .drone/push.sh
  environment:
    GH_DEPLOY_KEY:
      from_secret: GH_DEPLOY_KEY
---
kind: signature
hmac: 98c78842b0a4dd686d4e8c2f678415c6ba853295264ebcd061a6f763ba40ecda

...
