---
kind: pipeline
type: docker
name: update

platform:
  os: linux
  arch: amd64

steps:
- name: update
  image: php:8.5-cli
  commands:
  - apt-get update && apt-get install -y --no-install-recommends libzip-dev unzip
  - docker-php-ext-install zip
  - .drone/get-composer.sh
  - php composer.phar install
  - bin/update
- name: push
  image: alpine
  commands:
  - apk add git openssh
  - .drone/push.sh
  environment:
    GH_DEPLOY_KEY:
      from_secret: GH_DEPLOY_KEY
---
kind: signature
hmac: e1e6587cc473165b8af67abb41985e212fa0709889b496b34550589b8fb25033

...
